/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | '/chat/[sessionId]'
    >,
    '/chat/[sessionId]': RouteRecordInfo<
      '/chat/[sessionId]',
      '/chat/:sessionId',
      { sessionId: ParamValue<true> },
      { sessionId: ParamValue<false> },
      | never
    >,
    '/contacts': RouteRecordInfo<
      '/contacts',
      '/contacts',
      Record<never, never>,
      Record<never, never>,
      | '/contacts/[agentId]'
      | '/contacts/new'
    >,
    '/contacts/[agentId]': RouteRecordInfo<
      '/contacts/[agentId]',
      '/contacts/:agentId',
      { agentId: ParamValue<true> },
      { agentId: ParamValue<false> },
      | never
    >,
    '/contacts/new': RouteRecordInfo<
      '/contacts/new',
      '/contacts/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/providers': RouteRecordInfo<
      '/providers',
      '/providers',
      Record<never, never>,
      Record<never, never>,
      | '/providers/[providerId]'
      | '/providers/[providerId]/models/[modelId]'
      | '/providers/[providerId]/models/new'
      | '/providers/new'
    >,
    '/providers/[providerId]': RouteRecordInfo<
      '/providers/[providerId]',
      '/providers/:providerId',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | '/providers/[providerId]/models/[modelId]'
      | '/providers/[providerId]/models/new'
    >,
    '/providers/[providerId]/models/[modelId]': RouteRecordInfo<
      '/providers/[providerId]/models/[modelId]',
      '/providers/:providerId/models/:modelId',
      { providerId: ParamValue<true>, modelId: ParamValue<true> },
      { providerId: ParamValue<false>, modelId: ParamValue<false> },
      | never
    >,
    '/providers/[providerId]/models/new': RouteRecordInfo<
      '/providers/[providerId]/models/new',
      '/providers/:providerId/models/new',
      { providerId: ParamValue<true> },
      { providerId: ParamValue<false> },
      | never
    >,
    '/providers/new': RouteRecordInfo<
      '/providers/new',
      '/providers/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resources': RouteRecordInfo<
      '/resources',
      '/resources',
      Record<never, never>,
      Record<never, never>,
      | '/resources/[resourceId]'
    >,
    '/resources/[resourceId]': RouteRecordInfo<
      '/resources/[resourceId]',
      '/resources/:resourceId',
      { resourceId: ParamValue<true> },
      { resourceId: ParamValue<false> },
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/diagnostics'
      | '/settings/services'
    >,
    '/settings/diagnostics': RouteRecordInfo<
      '/settings/diagnostics',
      '/settings/diagnostics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/services': RouteRecordInfo<
      '/settings/services',
      '/settings/services',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/todo': RouteRecordInfo<
      '/todo',
      '/todo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/chat.vue': {
      routes:
        | '/chat'
        | '/chat/[sessionId]'
      views:
        | 'default'
    }
    'src/pages/chat/[sessionId].vue': {
      routes:
        | '/chat/[sessionId]'
      views:
        | never
    }
    'src/pages/contacts.vue': {
      routes:
        | '/contacts'
        | '/contacts/[agentId]'
        | '/contacts/new'
      views:
        | 'default'
    }
    'src/pages/contacts/[agentId].vue': {
      routes:
        | '/contacts/[agentId]'
      views:
        | never
    }
    'src/pages/contacts/new.vue': {
      routes:
        | '/contacts/new'
      views:
        | never
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
      views:
        | never
    }
    'src/pages/providers.vue': {
      routes:
        | '/providers'
        | '/providers/[providerId]'
        | '/providers/[providerId]/models/[modelId]'
        | '/providers/[providerId]/models/new'
        | '/providers/new'
      views:
        | 'default'
    }
    'src/pages/providers/[providerId].vue': {
      routes:
        | '/providers/[providerId]'
        | '/providers/[providerId]/models/[modelId]'
        | '/providers/[providerId]/models/new'
      views:
        | 'default'
    }
    'src/pages/providers/[providerId]/models/[modelId].vue': {
      routes:
        | '/providers/[providerId]/models/[modelId]'
      views:
        | never
    }
    'src/pages/providers/[providerId]/models/new.vue': {
      routes:
        | '/providers/[providerId]/models/new'
      views:
        | never
    }
    'src/pages/providers/new.vue': {
      routes:
        | '/providers/new'
      views:
        | never
    }
    'src/pages/resources.vue': {
      routes:
        | '/resources'
        | '/resources/[resourceId]'
      views:
        | 'default'
    }
    'src/pages/resources/[resourceId].vue': {
      routes:
        | '/resources/[resourceId]'
      views:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/diagnostics'
        | '/settings/services'
      views:
        | 'default'
    }
    'src/pages/settings/diagnostics.vue': {
      routes:
        | '/settings/diagnostics'
      views:
        | never
    }
    'src/pages/settings/services.vue': {
      routes:
        | '/settings/services'
      views:
        | never
    }
    'src/pages/todo.vue': {
      routes:
        | '/todo'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
