/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CodeMirrorView: typeof import('./components/base/CodeMirrorView.vue')['default']
    DustTransition: typeof import('./components/base/DustTransition.vue')['default']
    DustTransitionGroup: typeof import('./components/base/DustTransitionGroup.vue')['default']
    EditableField: typeof import('./components/base/EditableField.vue')['default']
    EditableTextarea: typeof import('./components/base/EditableTextarea.vue')['default']
    EmptyPlaceholder: typeof import('./components/base/EmptyPlaceholder.vue')['default']
    FileTypeIcon: typeof import('./components/base/FileTypeIcon.vue')['default']
    HighlightedCodeBlock: typeof import('./components/base/HighlightedCodeBlock.vue')['default']
    ImagePreviewHost: typeof import('./components/base/ImagePreviewHost.vue')['default']
    InlineEditActions: typeof import('./components/base/InlineEditActions.vue')['default']
    LogViewer: typeof import('./components/base/LogViewer.vue')['default']
    MarkdownContent: typeof import('./components/base/MarkdownContent.vue')['default']
    ResizeHandle: typeof import('./components/base/ResizeHandle.vue')['default']
    ResponsiveDialog: typeof import('./components/base/ResponsiveDialog/index.vue')['default']
    ResponsivePopover: typeof import('./components/base/ResponsivePopover/index.vue')['default']
    ResponsiveSplitSurface: typeof import('./components/base/ResponsiveSplitSurface/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SheetDrawer: typeof import('./components/base/SheetDrawer.vue')['default']
    UiActionButton: typeof import('./components/base/UiActionButton.vue')['default']
    UiBusyHost: typeof import('./components/base/UiBusyHost.vue')['default']
    UiConfirmHost: typeof import('./components/base/UiConfirmHost.vue')['default']
    UiDialog: typeof import('./components/base/UiDialog.vue')['default']
    UiEmptyState: typeof import('./components/base/UiEmptyState.vue')['default']
    UiField: typeof import('./components/base/UiField.vue')['default']
    UiListStatus: typeof import('./components/base/UiListStatus.vue')['default']
    UiMessageHost: typeof import('./components/base/UiMessageHost.vue')['default']
    WatsonIcon: typeof import('./components/base/WatsonIcon.vue')['default']
  }
}
