ALTER TABLE todo_task ADD COLUMN agent_id INTEGER REFERENCES agents(id) ON DELETE SET NULL;
ALTER TABLE todo_task ADD COLUMN depends_on TEXT NOT NULL DEFAULT '[]';
ALTER TABLE todo_task ADD COLUMN subagent_ids TEXT NOT NULL DEFAULT '[]';
ALTER TABLE todo_task ADD COLUMN phase TEXT NOT NULL DEFAULT 'draft';
